export enum ProvidersName {
  CART_REPOSITORY = 'CART_REPOSITORY',
  DATA_SOURCE = 'DATA_SOURCE',
  PRODUCT_REPOSITORY = 'PRODUCT_REPOSITORY',
  USER_REPOSITORY = 'USER_REPOSITORY',
  COVER_REPOSITORY = 'COVER_REPOSITORY',
  FILE_REPOSITORY = 'FILE_REPOSITORY',
}